

WITH CTE AS (

SELECT

TO_TIMESTAMP(STARTED_AT) AS START_TIME,
DATE(TO_TIMESTAMP(STARTED_AT)) AS STARTED,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED,
CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun')
THEN 'WEEKEND'
ELSE'BUSINESSDAY'
END AS DAY_TYPE,

CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS SEASON_OF_YEAR
 

{{ function1('STARTED_AT')}}
FROM 
{{ source('DEMO', 'BIKE') }}
WHERE STARTED_AT != 'started_at'

)


select * from CTE