

WITH CTE AS (

SELECT

TO_TIMESTAMP(STARTED_AT) AS START_TIME,
DATE(TO_TIMESTAMP(STARTED_AT)) AS STARTED,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED,
CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun')
THEN 'WEEKEND'
ELSE'BUSINESSDAY'
END AS DAY_TYPE,

{{get_season('STARTED_AT')}} AS SEASON_OF_YEAR
 
FROM 
{{ source('DEMO', 'BIKE') }}
WHERE STARTED_AT != 'started_at'


)

select * from CTE